### ISSUE TITLE
Values entered using their aliases ignore value type

### ISSUE THREAD

**Issue by rogovdm** [vadimdemedes/ronin#25]
- Have an option named «save», which is boolean and has alias named «s»
- executing two commands and checking type of that option «save»

```
cmd run --save=false 
cmd run --s=false 
```

save is type of boolean in first case and type of string in another.

P.S. Thanks for a lib, great work.

**Comment by vdemedes** [comment]
Thanks for opening up this issue, I will test it. Unfortunately, can't give any ETA, because I am very busy nowadays.

P.S. Glad you like Ronin! Psss, big update is coming soon!
