### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by daviddias** [vadimdemedes/ronin#29]
It would be great if ronin could use a `commands/index.js` or `commands/default.js` to reference a default command execution (instead of just printing help), for tools like nc, ncat, ucat, ls, and others that don't have necessary a command after the binary name.

(btw ronin is pretty awesome! :) )

**Comment by vdemedes** [comment]
Good point, it's been on my todo list for months. Unfortunately I'm very tight on time and at the moment I can't give Ronin an amount of attention it deserves. I hope to get to it sometime around february, so I think it's best for you to use some other library at the moment.

> (btw ronin is pretty awesome! :) )

Thank you, always glad to hear that ;)
