### ISSUE TITLE
[Docs] pass regular arguments to the command

### ISSUE THREAD

**Issue by daviddias** [vadimdemedes/ronin#30]
It took bit a bit to understand that in order to pass non 'option' arguments to a command, the trick is to pass extra args to the command method signature.

``` JavaScript
module.exports = Command.extend({
  desc: 'example',
  options: {},

  run: (arg1, arg2, arg3) => {
    console.log('args', arg1, arg2, arg3)
    })
  }
})
```

``` bash
$ some-cli command bananas, apples, rice
args bananas apples rice
```

Want me to PR this example to the README, to the website examples or any other docs? Might be helpful to others

**Comment by vdemedes** [comment]
I've been planning a rewrite of Ronin for a long time now, but unfortunately I'm struggling to allocate a time for this great project. I hope to get to it ASAP.

With that said, I appreciate your willing to help, but whole docs and website will be rewritten soon and I don't want your work to be lost. Thank you anyway ;)

**Comment by RichardLitt** [comment]
Hey @vdemedes. Offer to PR still there, even if our work will be lost. I had to search for this, too.
